---
resources:
- name: redisutils
  type: git
  source:
    uri: git@github.com:pivotal-cf/redisutils.git
    branch: master
    private_key: {{git-ssh-key}}
jobs:
- name: tests
  plan:
  - get: redisutils
    trigger: true
  - task: test
    file: redisutils/ci/test.yml
